/* Independent odd-only bit sieve. Prime list is generated by trial division. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#define ODDS 8388608ULL
static uint64_t number(const char *s){char *end;errno=0;uint64_t v=strtoull(s,&end,10);if(errno||*end||*s=='-')exit(2);return v;}
int main(int argc,char **argv){
    if(argc<4||argc>5)return 2;
    uint64_t a=number(argv[1]),b=number(argv[2]),limit=number(argv[3]);
    int list=argc==5&&!strcmp(argv[4],"--list");
    if(a<1||a>b||b>UINT32_MAX||limit<2||limit>2000||(list&&b-a>100000))return 2;
    unsigned ps[400],len=0;
    for(unsigned q=3;q<=limit;q+=2){int prime=1;for(unsigned d=3;d*d<=q;d+=2)if(q%d==0){prime=0;break;}if(prime)ps[len++]=q;}
    uint64_t *bits=malloc(ODDS/8);if(!bits)return 3;
    uint64_t count=0;int comma=0;
    printf("{\"algorithm\":\"odd-bit-segment\",\"root_first\":\"%llu\",\"root_last\":\"%llu\",\"p\":%llu,",(unsigned long long)a,(unsigned long long)b,(unsigned long long)limit);
    if(list)printf("\"roots\":[");
    for(uint64_t start=a|1ULL;start<=b;){
        uint64_t n=(b-start)/2+1;if(n>ODDS)n=ODDS;
        uint64_t words=(n+63)/64;memset(bits,0,words*8);
        for(unsigned j=0;j<len;j++){
            uint64_t q=ps[j],m=(start+q-1)/q*q;if(!(m&1))m+=q;
            for(uint64_t i=(m-start)/2;i<n;i+=q)bits[i/64]|=1ULL<<(i%64);
        }
        for(uint64_t w=0;w<words;w++){
            uint64_t good=~bits[w];if(w+1==words&&n%64)good&=(1ULL<<(n%64))-1;
            count+=__builtin_popcountll(good);
            if(list)while(good){unsigned bit=__builtin_ctzll(good);printf("%s\"%llu\"",comma?",":"",(unsigned long long)(start+2*(w*64+bit)));comma=1;good&=good-1;}
        }
        start+=2*n;
    }
    if(list)printf("],");printf("\"count\":\"%llu\",\"working_bytes\":%llu}\n",(unsigned long long)count,(unsigned long long)(ODDS/8));free(bits);return 0;
}
